### PR TITLE
feat: bump go requirement to 1.17

### PR DESCRIPTION
**Pull request by jahkeup**
*Issue #, if available:*

#44

*Description of changes:*

This updates the versions of Go used to allow dependencies to be updated (see #44).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jahkeup** [comment]
Updated the README with the updated version requirement.

**Review by austinvazquez — APPROVED** [review]

**Comment by austinvazquez** [comment]
@jahkeup wanted to check-in and see if we can get this merged together. The changes LGTM just need to resolve conflicts.

**Comment by jahkeup** [comment]
Yeah, definitely interested in getting this bump shipped. I'm short on time today, but will make an effort to get this rebased asap :)

**Review by kzys — APPROVED** [review]

**Comment by jahkeup** [comment]
Rebased!

Also added 1.19 to GitHub actions builds.

Not sure why the actions haven't kicked off :(

**Pull request merged**
